### ISSUE TITLE
HEAD-request for has_gravatar()

### ISSUE THREAD

**Issue by pix666** [twaddington/django-gravatar#18]
It will be great if function has_gravatar() send short HEAD-request instead of GET-request...

**Comment by twaddington** [comment]
Yeah, that's a reasonable request. I'll look into this.

**Comment by twaddington** [comment]
Fixed by 3d21ca6eb59e63a5457625a1ef70b6679bdbeb7f.

**Comment by twaddington** [comment]
Just pushed this change as version 1.3.0 of the library.
