### ISSUE TITLE
escaped html code in Django 1.9a

### ISSUE THREAD

**Issue by and-nothing-else** [twaddington/django-gravatar#21]
After update to 1.9 tag `{% gravatar email %}` return following code:
`&lt;img class=&quot;gravatar&quot; src=&quot;https://secure.gravatar.com…&quot; /&gt;`

**Comment by twaddington** [comment]
Django 1.9 is an alpha release. This plugin has not been tested with Django 1.9a.

**Comment by jarekwg** [comment]
This technically a bug.
The templatetag return strings should be marked safe:
https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.safestring.mark_safe

Django 1.9 is just being stricter when it comes to this.

**Comment by twaddington** [comment]
@jarekwg if you submit a pull request with passing tests I'd be happy to merge it in.

**Comment by twaddington** [comment]
This has been merged into master. I'll cut a new version and update PyPi shortly.

**Comment by twaddington** [comment]
Pushed to PyPi as 1.4.0: https://pypi.python.org/pypi/django-gravatar2/1.4.0
