### ISSUE TITLE
Support for libravatar ?

### ISSUE THREAD

**Issue by P-EB** [twaddington/django-gravatar#23]
Hey,

First, thanks for your work!

As gravatar is a proprietary, centralized solution, there is a free, decentralized alternative called libravatar. I don't know how hard it would be to provide also support for it, but as libravatar fallbacks on gravatar when nothing is found, so it could offer a wider compatibility to your library.

Would you be interested in?

https://www.libravatar.org/

Cheers !

-- 
PEB

**Comment by twaddington** [comment]
Thanks PEB but I'm not really interested in adding support for this at the moment.
