### ISSUE TITLE
tests not in pypi sdist

### ISSUE THREAD

**Issue by dvzrv** [twaddington/django-gravatar#32]
Hi! I'm packaging django-gravatar for Arch Linux.
We usually use pypi for tracking new versions and building from sources.

However, when building 1.4.2 I realized, that the test application is missing from the sdist on pypi.
It would be very awesome, if it could be added. Thank you!

**Comment by twaddington** [comment]
Thanks @dvzrv, I'm not familiar with packaging django plugins for Linux. What would be the reason to package the test application? Wouldn't that only be relevant to developers?

**Comment by twaddington** [comment]
I believe I've resolved this. Please try version 1.4.3 on PyPi.
