### ISSUE TITLE
Missing tag for 1.4.4

### ISSUE THREAD

**Issue by dvzrv** [twaddington/django-gravatar#40]
Hi! :wave: 

I package this project for Arch Linux.
We have started to no longer rely on sdist tarballs hosted on PyPI due to various issues (https://rfc.archlinux.page/0020-sources-for-python-packaging/) and are switching all packages to either git sources or upstream provided, auto-generated tarballs.

While doing so, I noticed that the 1.4.4 release is not tagged in this repository.
Maybe you forgot to push the tag?
Either way: It would be much appreciated if you could add a tag for that particular version. :pray:

**Comment by dvzrv** [comment]
From what I can tell at a quick glance, ed123f849b5207e11efdfb1b2b0235baa41df356 is likely 1.4.4

**Comment by twaddington** [comment]
Thanks for bringing this to my attention. I've pushed a tag for 1.4.4.
